### PR TITLE
Added address and teachers model, basic implementation of routes and …

### PR DESCRIPTION
**Pull request by jioblack**
…controller

## Description
Added a basic implementation of a teacher and address model, basic routes and controller.

### CODE REVIEW

**Comment by jioblack** [comment]
This is a request to add basic models for the backend, routes, and controllers

**Review by Theshedman — APPROVED** [review]

**Review by alexzender45 — APPROVED** [review]
Nice job

**Review by anje123 — APPROVED** [review]
Good job

**Review by taiwosunday99 — CHANGES_REQUESTED** [review]
Considering the app.controllers,  in Teachers Application model, while not separate the Fullname to have LastName and FirstName instead. And I notice no req body for address street, num, state and country. Check this out before approving.

**Review by jioblack — COMMENTED** [review]
Acknowledge

**Review by taiwosunday99 — APPROVED** [review]

**Pull request merged**
