### PR TITLE
Setting up project for express REST API

### PR DESCRIPTION
**Pull request by jioblack**
## Description
Setup the REST API directory structure [controllers, models, routes]
Implemented babel for transcompilation of src folder
Implemented nodemon to watch changes.
Included a docker-compose.yml file to help setup mongodb using docker image.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
No test framework was used, but app was compiled and run perfectly

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by taiwosunday99 — APPROVED** [review]
The necessary settings has being made and should be ready to merge to develop

**Review by alexzender45 — APPROVED** [review]
Nice job

**Review by alexzender45 — APPROVED** [review]

**Review by Theshedman — APPROVED** [review]

**Review by alexzender45 — CHANGES_REQUESTED** [review]
Nice job this pull request should get merged

**Review by alexzender45 — APPROVED** [review]

**Review by alexzender45 — APPROVED** [review]
Merge please

**Review by alexzender45 — COMMENTED** [review]
good too go

**Pull request merged**
